# -*- coding: utf-8 -*-
"""Arshad_Chettan_Submit .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hMOfvMiN43XvIEuXC-LiuytzUCxW5JDU
"""





"""## **Getting the data into the environment**"""

from pdfminer.high_level import extract_text

aud = extract_text('/content/auditor-resume-example.pdf')
ba = extract_text('/content/ENTRY-LEVEL-BUSINESS-ANALYST-Resume-Example.pdf')
resume_data = extract_text('/content/bank_teller_resume_example.pdf')



"""## **Below cell is the UDF function to fetch the important details of candidates from their resume**"""

def get_data_from_resume(x):
  name_span = re.search('\n*[A-Z][A-Za-z]+\s[A-Z][A-Za-z]+|\n*[A-Z][A-Za-z]+\n[A-Z][A-Za-z]+|\n*[A-Z][\s]*[A-Za-z]|\n*[A-Za-z\s]{3,}[\s]+[A-Za-z\s]+|\n*[A-Za-z\s]{3,}\n[A-Za-z\s]+\n',x).span()
  name = x[name_span[0]:name_span[1]]


  email = re.findall('\n{0,}.+@.+\.\s*.+',x)


  mob_span = re.search('[0-9]{10}|[0-9]{3}-[0-9]{3,}-[0-9]{3,}|([0-9]\s){3}\s*-\s*([0-9]\s){3,}\s*-\s*([0-9]\s){3,}',x).span()
  mobile_num = x[mob_span[0]:mob_span[1]]


  # EXPERIENCE CODE 

  experience = re.findall('[A-Z][a-zA-z\s\',\|]+[0-9]+\s+[-Tt]?[oO]?\s+[0-9]+\n\n | [A-Z][a-zA-Z\s,\'\|]+\n\n[A-Za-z\s\',\|]+\s+[0-9]+\s*[-Tt]?[oO]?\s+[0-9]+\n\n',x)



  # EDUCATION CODE

  education = re.findall('.*[uU]\s?[nN]\s?[iI]\s?[vV]\s?.*\n{1,3}.+',x)

  return {'name':name,'email':email,'mobile_num':mobile_num,'experience':experience,'edu':education}

"""## **Below cell has the code to write the fetched data from the resumes to an excel file**"""

import pandas as pd
df=pd.DataFrame()
for i in [aud,ba,resume_data]:
  df=pd.concat([df,pd.DataFrame.from_dict(get_data_from_resume(i), orient='index').T],axis=0)

df


from google.colab import files
df.to_excel('written_resume_data.xlsx')
files.download('written_resume_data.xlsx')